### ISSUE TITLE
Use updated version of StopsGB?

### ISSUE THREAD

**Issue by josh-rhodes** [Living-with-machines/beyondthetracks#1]
I've pulled in the StopsGB dataset from the BL Repo [here](https://bl.iro.bl.uk/concern/datasets/0abea1b1-2a43-4422-ba84-39b354c8bb09) but know that work was done by @andrewphilipsmith, @kmcdono2, and @mcollardanuy and others to clean up StopsGB. Is there an updated version somewhere that we can use, or do we use the public version?

**Comment by kmcdono2** [comment]
@josh-rhodes - Alas, we didn't do any more work to improve it, so what you've got is good to use!

**Comment by josh-rhodes** [comment]
Ah my mistake! ok!
